### PR TITLE
Add multi-language support

### LINKED ISSUE #5: Allow generate code-of-conduct.md for difference languages
https://www.contributor-covenant.org/translations.html

### PR DESCRIPTION
**Pull request by brandon93s**
**Notes:**
- Implement multi-language support
- Default language to `en`

**Caveats:**
- AVA now runs serially to combat [conf](https://github.com/sindresorhus/conf) change interference 

Closes #5

### CODE REVIEW

**Comment by brandon93s** [comment]
@sindresorhus I considered a few other options here:

1. Remove conduct `md` from the repo altogether, and load the requested language from the Contributor Covenant repo over http. Would allow new languages to flow through automatically and results could be cached on the local machine. Validation becomes an http request failure, and showing supported languages a bit more tricky.

2. Add a bin/update-languages.js script to the repo that imports translations when run. This approach keeps all data local to the project but provides a quick way to pull in new languages in the future. 

Ultimately settled on the simple approach of local files. New translations are infrequent and didn't seem to justify any convenience scripting for future synchronization. Thoughts / feedback?

**Comment by brandon93s** [comment]
@sindresorhus [Indonesian](https://github.com/ContributorCovenant/contributor_covenant/blob/master/content/version/1/4/code-of-conduct.id.md) has been added recently. If there is interest in this landing, I will update with the latest files. Otherwise I'm going to go ahead and close this out.

Thanks!

**Comment by sindresorhus** [comment]
@brandon93s Sorry, I missed this. I'm still interested in adding this if you are?

**Comment by sindresorhus** [comment]
> Ultimately settled on the simple approach of local files. New translations are infrequent and didn't seem to justify any convenience scripting for future synchronization. Thoughts / feedback?

That sounds fine. They rarely update it.

**Comment by brandon93s** [comment]
Yes, definitely still interested. I will open a separate PR when I have time - this branch is bricked (whoops!).

**Pull request closed without merging**
